---
name: Savings Tracker
version: "1.0.4"
slug: savings-tracker
description: A modern web-based savings tracker with calendar interface and progress visualization
url: "https://github.com/Alex-Whyatt/ha-savings-addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ingress: true
panel_icon: "mdi:cash-multiple"
ports:
  80/tcp: null
webui: "[PROTO:ssl]://[HOST]:[PORT:80]"
map:
  - data:rw
